# ~/.config/starship.toml

add_newline = true
command_timeout = 1000

# Two-line prompt:
format = """
$directory
$all$character
"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vimcmd_symbol = "[](bold blue) "

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = '([\[$all_status$ahead_behind\]]($style) )'

[username]
show_always = false
style_user = "bold yellow"
format = "[$user]($style) "

[hostname]
ssh_only = true
style = "bold dimmed green"
format = "on [$hostname]($style) "

[cmd_duration]
min_time = 200
format = "took [$duration]($style) "

[time]
disabled = true

[aws]
disabled = true

[kubernetes]
disabled = true
