format = '$all$username[::](bold blue)$hostname$character'

[kubernetes]
disabled = false

[username]
disabled = false
show_always = true
format = '[$user](bold green)'

[hostname]
ssh_only = false
ssh_symbol = ' ğŸŒ'
format = '[$hostname](bold red)[$ssh_symbol](bold blue)'
trim_at = '.local'
disabled = false
